name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test on current LTS versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enable caching for npm dependencies

      - name: Install dependencies
        run: npm ci # Use ci for cleaner installs in CI

      # Build step is needed to ensure TS compiles and svg2png.js exists for bin linking
      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test
